const fs = require('fs');
const path = require('path');
const logger = require('../utils/logger');

/**
 * Read Azure activity logs from the dataset file.
 * This connects the Week 5 Azure Security Dataset to the API layer.
 */
const getActivityLogs = async (req, res, next) => {
  try {
    const limit = parseInt(req.query.limit, 10) || 50;
    const statusFilter = req.query.status;
    const callerFilter = req.query.caller;

    // Default to the file generated by data-collection/azure_log_collector.py
    const defaultPath = path.join(
      __dirname,
      '../../../data-collection/azure_activity_logs.json'
    );

    const logFilePath = process.env.AZURE_ACTIVITY_LOG_FILE || defaultPath;

    if (!fs.existsSync(logFilePath)) {
      return res.status(404).json({
        error: 'Azure activity log file not found',
        pathTried: logFilePath
      });
    }

    const raw = fs.readFileSync(logFilePath, 'utf8');
    const allLogs = JSON.parse(raw);

    let filtered = allLogs;

    if (statusFilter) {
      filtered = filtered.filter(
        (e) =>
          String(e.status || '').toLowerCase() ===
          String(statusFilter).toLowerCase()
      );
    }

    if (callerFilter) {
      filtered = filtered.filter((e) =>
        String(e.caller || '')
          .toLowerCase()
          .includes(String(callerFilter).toLowerCase())
      );
    }

    // Sort by timestamp descending (most recent first)
    filtered.sort((a, b) => {
      const ta = a.timestamp ? new Date(a.timestamp).getTime() : 0;
      const tb = b.timestamp ? new Date(b.timestamp).getTime() : 0;
      return tb - ta;
    });

    const result = filtered.slice(0, limit);

    logger.info('Returned Azure activity logs', {
      count: result.length,
      totalAvailable: filtered.length
    });

    res.json({
      count: result.length,
      totalAvailable: filtered.length,
      data: result
    });
  } catch (error) {
    logger.error('Error reading Azure activity logs:', error);
    next(error);
  }
};

module.exports = {
  getActivityLogs
};


